### ISSUE TITLE
harvest_metadata_no_pages is harvesting pages

### ISSUE THREAD

**Issue by mlhale7** [markpbaggett/whitebread#1]
When harvesting metadata using -o harvest_metadata_no_pages, I'm getting pages in the results. See the screenshot for commands for Tennessee Farm and Home Science (agrtfhs) and the Extension Special Circulars(agrutesc). agrutesc only has 225 objects and agrtfhs has 135 objects.

<img width="571" alt="whitebread_nopages" src="https://user-images.githubusercontent.com/12545660/65164863-ad63b900-da0b-11e9-8224-4374ed6dc017.png">

**Comment by markpbaggett** [comment]
@mlhale7, I don't know anything about this, but the problem is with the relationships API on porter.  When you try to do a get request versus it, it returns a 401 unauthorized.  In other words, this isn't a problem with the code.  It's a problem with permissions on the server.

**Comment by mlhale7** [comment]
@markpbaggett - thanks for this. Should I get in contact with Paul or Emily about this problem?

**Comment by markpbaggett** [comment]
I'd talk to Don or Paul. They are responsible for Fedora on Porter.

Best,
Mark


________________________________
